CREATE TABLE CATEGORY(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    NAME VARCHAR(255) NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)